export const billingCycles = [
  'Monthly',
  'Yearly',
  'Quarterly',
  'Weekly',
  'Bi-Weekly',
  'Semi-Annually',
  'Biennially',
  'One-Time',
  "Other"
];

export const subscriptionTypes = [
  'Streaming',
  'Domain',
  'Software',
  'Magazine',
  'Cloud Storage',
  'E-Learning',
  'Gaming',
  'Fitness',
  'Subscription Boxes',
  'Food Delivery',
  'Newsletters',
  'Online Courses',
  'Music',
  'Books',
  'Cloud Services',
  'Web Hosting',
  'VPN',
  'App Services',
  'Social Media Management',
  'Podcast',
  'Online Dating',
  'Telehealth',
  'Printing Services',
  'Online Communities',
  'Stock Photos',
  'Tech Support',
  'Virtual Events',
  'Home Security',
  'Digital Tools',
  'Art/Creative Services',
  'Investment/Finance',
  'Language Learning',
  'Fitness Equipment',
  'Pet Services',
  'Meal Kits',
  'Auto-Insurance',
  'Car Rentals',
  'Mental Health',
  'Business Tools',
  'Personalized Nutrition',
  'Virtual Assistants',
  'Legal Services',
  'Fashion/Clothing',
  'Beauty & Grooming',
  'Event Planning',
  'Digital Marketing',
  'Productivity Tools',
  'Parenting',
  'Outdoor Gear',
  'Photography',
  'DIY Craft Kits',
  'Craft Beverages',
  'Home Decor',
  'Luxury Goods',
  'Smart Home Devices',
  'Mobile Games',
  'Voice Assistants',
  'Webinars',
  'Online Tutoring',
  'Car Maintenance',
  'Self-Care',
  'Digital Art',
  'Sustainability',
  'Research Papers',
  'Herbal Medicine',
  'DIY Repairs',
  'Adventure Travel',
  'Insurance',
  'Charity/Non-Profit',
  'Tech Gadgets',
  'Student Services',
  'SaaS Tools',
  'Real Estate',
  'Sports Coaching',
  'Other'
];

export const paymentMethods = [
  'Credit Card',
  'Debit Card',
  'Prepaid Card',
  'PayPal',
  'Apple Pay',
  'Google Pay',
  'Samsung Pay',
  'Venmo',
  'Stripe',
  'Bank Transfer',
  'ACH Transfer',
  'Cryptocurrency',
  'Bitcoin',
  'Ethereum',
  'Gift Card',
  'Cash on Delivery',
  'Wire Transfer',
  'eCheck',
  'Amazon Pay',
  'Alipay',
  'WeChat Pay',
  'Zelle',
  'Square',
  'Klarna',
  'Afterpay',
  'Shop Pay',
  'Braintree',
  'MasterPass',
  'Visa Checkout',
  'Cryptocurrency Wallets',
  'Buy Now, Pay Later',
  'Mobile Wallets',
  'Cash',
  'Payment Link',
  'Other'
];

export const currencyCodes = [
  'AFN', 'ALL', 'DZD', 'EUR', 'AOA', 'XCD', 'ARS', 'AMD', 'AUD', 'EUR',
  'AZN', 'BSD', 'BHD', 'BDT', 'BBD', 'BYN', 'EUR', 'BZD', 'XOF', 'BTN',
  'BOB', 'BAM', 'BWP', 'BRL', 'BND', 'BGN', 'XOF', 'BIF', 'CVE', 'KHR',
  'CAF', 'CAD', 'CAF', 'CAF', 'CLP', 'CNY', 'COP', 'KMF', 'CAF', 'CDF',
  'CRC', 'HRK', 'CUP', 'EUR', 'CZK', 'DKK', 'DJF', 'XCD', 'DOP', 'USD',
  'EGP', 'USD', 'CAF', 'ERN', 'EUR', 'SZL', 'ETB', 'FJD', 'EUR', 'EUR',
  'CAF', 'GMD', 'GEL', 'EUR', 'GHS', 'EUR', 'XCD', 'GTQ', 'GNF', 'XOF',
  'GYD', 'HTG', 'HNL', 'HUF', 'ISK', 'INR', 'IDR', 'IRR', 'IQD', 'ILS',
  'EUR', 'JPY', 'JOD', 'KZT', 'KES', 'AUD', 'KPW', 'KRW', 'KWD', 'KGS',
  'LAK', 'EUR', 'LBP', 'LSL', 'LRD', 'LYD', 'CHF', 'EUR', 'MGA', 'MWK',
  'MYR', 'MVR', 'XOF', 'EUR', 'USD', 'MRU', 'MUR', 'MXN', 'USD', 'MDL',
  'EUR', 'MNT', 'EUR', 'MAD', 'MZN', 'MMK', 'NAD', 'AUD', 'NPR', 'EUR',
  'NZD', 'NIO', 'XOF', 'NGN', 'MKD', 'NOK'
];
