export const billingCycles = [
  'Monthly',
  'Yearly',
  'Quarterly',
  'Weekly',
  'Bi-Weekly',
  'Semi-Annually',
  'Biennially',
  'One-Time',
  "Other"
];

export const subscriptionTypes = [
  'Streaming',
  'Domain',
  'Software',
  'Magazine',
  'Cloud Storage',
  'E-Learning',
  'Gaming',
  'Fitness',
  'Subscription Boxes',
  'Food Delivery',
  'Newsletters',
  'Online Courses',
  'Music',
  'Books',
  'Cloud Services',
  'Web Hosting',
  'VPN',
  'App Services',
  'Social Media Management',
  'Podcast',
  'Online Dating',
  'Telehealth',
  'Printing Services',
  'Online Communities',
  'Stock Photos',
  'Tech Support',
  'Virtual Events',
  'Home Security',
  'Digital Tools',
  'Art/Creative Services',
  'Investment/Finance',
  'Language Learning',
  'Fitness Equipment',
  'Pet Services',
  'Meal Kits',
  'Auto-Insurance',
  'Car Rentals',
  'Mental Health',
  'Business Tools',
  'Personalized Nutrition',
  'Virtual Assistants',
  'Legal Services',
  'Fashion/Clothing',
  'Beauty & Grooming',
  'Event Planning',
  'Digital Marketing',
  'Productivity Tools',
  'Parenting',
  'Outdoor Gear',
  'Photography',
  'DIY Craft Kits',
  'Craft Beverages',
  'Home Decor',
  'Luxury Goods',
  'Smart Home Devices',
  'Mobile Games',
  'Voice Assistants',
  'Webinars',
  'Online Tutoring',
  'Car Maintenance',
  'Self-Care',
  'Digital Art',
  'Sustainability',
  'Research Papers',
  'Herbal Medicine',
  'DIY Repairs',
  'Adventure Travel',
  'Insurance',
  'Charity/Non-Profit',
  'Tech Gadgets',
  'Student Services',
  'SaaS Tools',
  'Real Estate',
  'Sports Coaching',
  'Other'
];

